//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEES_MEMBERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMITTEES_MEMBERS()
        {
            this.COMM_MEM_PROV = new HashSet<COMM_MEM_PROV>();
            this.COMM_MEM_RANKS = new HashSet<COMM_MEM_RANKS>();
        }
    
        public long ID { get; set; }
        public long COMM_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string USER_POSITION { get; set; }
        public Nullable<long> USER_RANK { get; set; }
        public Nullable<bool> APPEARS { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMM_MEM_PROV> COMM_MEM_PROV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMM_MEM_RANKS> COMM_MEM_RANKS { get; set; }
        public virtual COMMITTEES COMMITTEES { get; set; }
        public virtual COMMITTEES_RANKS COMMITTEES_RANKS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
