//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEES_RANKS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMITTEES_RANKS()
        {
            this.COMMITTEES = new HashSet<COMMITTEES>();
            this.COMMITTEES_MEMBERS = new HashSet<COMMITTEES_MEMBERS>();
        }
    
        public long ID { get; set; }
        public string NAME_A { get; set; }
        public string NAME_L { get; set; }
        public int ORDER_NO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMITTEES> COMMITTEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMITTEES_MEMBERS> COMMITTEES_MEMBERS { get; set; }
    }
}
