//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMITTEES()
        {
            this.CMITS_FIL_PERD = new HashSet<CMITS_FIL_PERD>();
            this.COMMITTEES_MEMBERS = new HashSet<COMMITTEES_MEMBERS>();
            this.ST_REQ_COMMITTEES = new HashSet<ST_REQ_COMMITTEES>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> PROV_ID { get; set; }
        public string PRESIDENT_NAME { get; set; }
        public Nullable<long> PRESIDENT_RANK { get; set; }
        public string PRESIDENT_POSITION { get; set; }
        public long CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMITS_FIL_PERD> CMITS_FIL_PERD { get; set; }
        public virtual COMMITTEES_RANKS COMMITTEES_RANKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMITTEES_MEMBERS> COMMITTEES_MEMBERS { get; set; }
        public virtual ULP_DEPARTMENTS ULP_DEPARTMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_REQ_COMMITTEES> ST_REQ_COMMITTEES { get; set; }
    }
}
