//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATION
    {
        public long ID { get; set; }
        public long EMP_NO { get; set; }
        public long QUAL_ID { get; set; }
        public Nullable<long> REQ_ID { get; set; }
        public string EMP_QUAL_FILE_NAME { get; set; }
        public string EMP_QUAL_FILE_PATH { get; set; }
        public long CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        public virtual CERTIFICATE_TYPES CERTIFICATE_TYPES { get; set; }
    }
}
