//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public long ID { get; set; }
        public long EMP_NO { get; set; }
        public string EMPLOYEE_FIRST_NAME { get; set; }
        public string EMPLOYEE_FATHER_NAME { get; set; }
        public string EMPLOYEE_GRAND_NAME { get; set; }
        public string EMPLOYEE_FAMILY_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public long SOLDIER_NO { get; set; }
        public long IDENTITY_NO { get; set; }
        public System.DateTime EMP_H_DATE { get; set; }
        public Nullable<long> GENDER { get; set; }
        public Nullable<long> PHONE { get; set; }
        public Nullable<long> PROV_ID { get; set; }
        public long DEPT_ID { get; set; }
        public Nullable<long> DIV_ID { get; set; }
        public Nullable<long> SECTION_ID { get; set; }
        public string EMAIL { get; set; }
        public long CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    }
}
