//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_SERVICE
    {
        public long ID { get; set; }
        public Nullable<long> REQ_ID { get; set; }
        public Nullable<System.DateTime> FIELD_START_DATE { get; set; }
        public Nullable<System.DateTime> FIELD_START_DATE_H { get; set; }
        public Nullable<System.DateTime> FIELD_END_DATE { get; set; }
        public Nullable<System.DateTime> FIELD_END_DATE_H { get; set; }
        public string LOCATION { get; set; }
        public Nullable<double> FIELD_POINTS { get; set; }
        public string FIELD_FILE_NAME { get; set; }
        public string FIELD_FILE_PATH { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual REQUESTS REQUESTS { get; set; }
    }
}
