//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPS()
        {
            this.GROUPS_PERMISSIONS = new HashSet<GROUPS_PERMISSIONS>();
            this.USERS_GROUPS = new HashSet<USERS_GROUPS>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public string NAME_A { get; set; }
        public string DESCRIPTION { get; set; }
        public string CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string NAME_L { get; set; }
        public Nullable<int> STATUSES_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_PERMISSIONS> GROUPS_PERMISSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_GROUPS> USERS_GROUPS { get; set; }
    }
}
