//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABORATORY_ANALYSIS
    {
        public long ID { get; set; }
        public Nullable<long> REQ_ID { get; set; }
        public string LAB_FILE_NAME { get; set; }
        public string LAB_FILE_PATH { get; set; }
        public Nullable<long> ANALYSIS_RESULT { get; set; }
        public string CODE { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual REQUESTS REQUESTS { get; set; }
    }
}
