//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MEFDBEs : DbContext
    {
        public MEFDBEs()
            : base("name=MEFDBEs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CERTIFICATE_TYPES> CERTIFICATE_TYPES { get; set; }
        public virtual DbSet<CMITS_FIL_PERD> CMITS_FIL_PERD { get; set; }
        public virtual DbSet<COMM_MEM_PROV> COMM_MEM_PROV { get; set; }
        public virtual DbSet<COMM_MEM_RANKS> COMM_MEM_RANKS { get; set; }
        public virtual DbSet<COMMITTEES> COMMITTEES { get; set; }
        public virtual DbSet<COMMITTEES_MEMBERS> COMMITTEES_MEMBERS { get; set; }
        public virtual DbSet<COMMITTEES_RANKS> COMMITTEES_RANKS { get; set; }
        public virtual DbSet<COURSES> COURSES { get; set; }
        public virtual DbSet<COURSES_EXCEPTION_TYPE> COURSES_EXCEPTION_TYPE { get; set; }
        public virtual DbSet<DEDUCTING_DECISIONS_TYPES> DEDUCTING_DECISIONS_TYPES { get; set; }
        public virtual DbSet<DEPARTMENTS> DEPARTMENTS { get; set; }
        public virtual DbSet<DIVISIONS> DIVISIONS { get; set; }
        public virtual DbSet<DT_DEPARTMENTS> DT_DEPARTMENTS { get; set; }
        public virtual DbSet<EDUCATION> EDUCATION { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<FIELD_SERVICE> FIELD_SERVICE { get; set; }
        public virtual DbSet<FILT_PER_RANK> FILT_PER_RANK { get; set; }
        public virtual DbSet<FILTRATION_PERIODS> FILTRATION_PERIODS { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<GROUPS_PERMISSIONS> GROUPS_PERMISSIONS { get; set; }
        public virtual DbSet<LABORATORY_ANALYSIS> LABORATORY_ANALYSIS { get; set; }
        public virtual DbSet<LT_CITIES> LT_CITIES { get; set; }
        public virtual DbSet<LT_MFP_TYPES> LT_MFP_TYPES { get; set; }
        public virtual DbSet<LT_PROVNCITY> LT_PROVNCITY { get; set; }
        public virtual DbSet<MFP> MFP { get; set; }
        public virtual DbSet<MFP_PROCEDURES> MFP_PROCEDURES { get; set; }
        public virtual DbSet<MSGS_SYS_D> MSGS_SYS_D { get; set; }
        public virtual DbSet<MSGS_SYS_H> MSGS_SYS_H { get; set; }
        public virtual DbSet<NO_FILT_REQ> NO_FILT_REQ { get; set; }
        public virtual DbSet<POINTS_TYPE> POINTS_TYPE { get; set; }
        public virtual DbSet<PROCEDURES_TYPE> PROCEDURES_TYPE { get; set; }
        public virtual DbSet<PROMOTION_TESTS> PROMOTION_TESTS { get; set; }
        public virtual DbSet<PROMOTIONS> PROMOTIONS { get; set; }
        public virtual DbSet<QUALIFICATIONS> QUALIFICATIONS { get; set; }
        public virtual DbSet<REQUEST_PROCEDURES> REQUEST_PROCEDURES { get; set; }
        public virtual DbSet<REQUESTS> REQUESTS { get; set; }
        public virtual DbSet<REQUESTS_STAGES> REQUESTS_STAGES { get; set; }
        public virtual DbSet<REQUESTS_STATUSES> REQUESTS_STATUSES { get; set; }
        public virtual DbSet<SECTIONS> SECTIONS { get; set; }
        public virtual DbSet<SENIORITY> SENIORITY { get; set; }
        public virtual DbSet<SERVICE_FILE> SERVICE_FILE { get; set; }
        public virtual DbSet<ST_MRANK> ST_MRANK { get; set; }
        public virtual DbSet<ST_MULT_UNIT> ST_MULT_UNIT { get; set; }
        public virtual DbSet<ST_REQ_COMMITTEES> ST_REQ_COMMITTEES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ULP_DEPARTMENTS> ULP_DEPARTMENTS { get; set; }
        public virtual DbSet<ULP_EMPLOYEES> ULP_EMPLOYEES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<USERS_GROUPS> USERS_GROUPS { get; set; }
        public virtual DbSet<USERS_PERMISSIONS> USERS_PERMISSIONS { get; set; }
        public virtual DbSet<USERS_SETTINGS> USERS_SETTINGS { get; set; }
        public virtual DbSet<VACANT_JOBS> VACANT_JOBS { get; set; }
        public virtual DbSet<LT_PROCEDURES_TYPES> LT_PROCEDURES_TYPES { get; set; }
        public virtual DbSet<LT_NO_FILT_REASON> LT_NO_FILT_REASON { get; set; }
        public virtual DbSet<ST_TRANS_TYPES> ST_TRANS_TYPES { get; set; }
        public virtual DbSet<STATUSES> STATUSES { get; set; }
        public virtual DbSet<EMP_PERMS_VU> EMP_PERMS_VU { get; set; }
        public virtual DbSet<ULP_DEPARTMENTS_VU> ULP_DEPARTMENTS_VU { get; set; }
    }
}
