//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGS_SYS_H
    {
        public long ID { get; set; }
        public string SUBJECT { get; set; }
        public long FROM_PROV_ID { get; set; }
        public bool STATUS { get; set; }
    }
}
