//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGS_SYS_D
    {
        public long ID { get; set; }
        public long MSGS_SYS_H_ID { get; set; }
        public string TEXT { get; set; }
        public string ATT_NAME { get; set; }
        public string ATT_EXT { get; set; }
        public long FROM_PROV_ID { get; set; }
        public long TO_PROV_ID { get; set; }
        public int CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime CREATION_DATE_H { get; set; }
    }
}
