//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINTS_TYPE
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public long POINTS { get; set; }
        public string SUCCESS_PERCENTAGE { get; set; }
    }
}
