//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTIONS
    {
        public long ID { get; set; }
        public long EMP_NO { get; set; }
        public long RANK_ID { get; set; }
        public Nullable<System.DateTime> RANK_DATE { get; set; }
        public Nullable<System.DateTime> RANK_DATE_H { get; set; }
        public Nullable<System.DateTime> CANDIDATE_DATE { get; set; }
        public Nullable<System.DateTime> CANDIDATE_DATE_H { get; set; }
        public Nullable<System.DateTime> MERIT_DATE { get; set; }
        public Nullable<System.DateTime> MERIT_DATE_H { get; set; }
        public long SOLDIER_NO2 { get; set; }
        public Nullable<long> REQ_ID { get; set; }
        public Nullable<long> MOFADLAH_NO { get; set; }
        public Nullable<long> FILTRATION_PERIODS_ID { get; set; }
        public Nullable<long> DECISION_ID { get; set; }
        public string DECISION_ATTACH_FILE_NAME { get; set; }
        public string DECISION_ATTACH_FILE_PATH { get; set; }
        public string DECISION_DATE_H { get; set; }
        public Nullable<System.DateTime> DECISION_DATE { get; set; }
        public long CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    }
}
