//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALIFICATIONS
    {
        public long ID { get; set; }
        public Nullable<long> REQ_ID { get; set; }
        public Nullable<long> CERTIFICATE_TYPE_ID { get; set; }
        public long QUALIFICATION_EXCEPTION { get; set; }
        public string QUAL_REASON { get; set; }
        public string QUAL_FILE_NAME { get; set; }
        public string QUAL_FILE_PATH { get; set; }
        public Nullable<double> QUAL_POINTS { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual CERTIFICATE_TYPES CERTIFICATE_TYPES { get; set; }
        public virtual REQUESTS REQUESTS { get; set; }
    }
}
