//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUESTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUESTS()
        {
            this.COURSES = new HashSet<COURSES>();
            this.FIELD_SERVICE = new HashSet<FIELD_SERVICE>();
            this.LABORATORY_ANALYSIS = new HashSet<LABORATORY_ANALYSIS>();
            this.NO_FILT_REQ = new HashSet<NO_FILT_REQ>();
            this.PROMOTION_TESTS = new HashSet<PROMOTION_TESTS>();
            this.QUALIFICATIONS = new HashSet<QUALIFICATIONS>();
            this.SENIORITY = new HashSet<SENIORITY>();
            this.SERVICE_FILE = new HashSet<SERVICE_FILE>();
            this.ST_REQ_COMMITTEES = new HashSet<ST_REQ_COMMITTEES>();
        }
    
        public long ID { get; set; }
        public long EMP_NO { get; set; }
        public Nullable<long> CURRENT_RANK_ID { get; set; }
        public Nullable<long> NEXT_RANK_ID { get; set; }
        public long REQ_STAGE_ID { get; set; }
        public long REQ_STATE_ID { get; set; }
        public Nullable<System.DateTime> REQ_DATE { get; set; }
        public Nullable<System.DateTime> REQ_DATE_H { get; set; }
        public Nullable<long> FILTRATION_PERIODS_ID { get; set; }
        public Nullable<double> TOTAL_FIELD_SERVICE { get; set; }
        public Nullable<double> TOTAL_ALL_POINTS { get; set; }
        public string REASON { get; set; }
        public string COMITES_NOTES { get; set; }
        public Nullable<long> LAGNA_ACCEPT { get; set; }
        public string LAGNA_FILE_NAME { get; set; }
        public string LAGNA_FILE_PATH { get; set; }
        public Nullable<long> DECISION_ID { get; set; }
        public string DECISION_DATE_H { get; set; }
        public Nullable<System.DateTime> DECISION_DATE { get; set; }
        public string FILE_SERVICE_NOTES { get; set; }
        public string FILE_SERVICE_FILE_NAME { get; set; }
        public string FILE_SERVICE_FILE_PATH { get; set; }
        public string NEW_RANK_DATE_H { get; set; }
        public Nullable<System.DateTime> NEW_RANK_DATE { get; set; }
        public Nullable<long> OLD_REQ_STAGE_ID { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<long> UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSES> COURSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIELD_SERVICE> FIELD_SERVICE { get; set; }
        public virtual FILTRATION_PERIODS FILTRATION_PERIODS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LABORATORY_ANALYSIS> LABORATORY_ANALYSIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NO_FILT_REQ> NO_FILT_REQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMOTION_TESTS> PROMOTION_TESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALIFICATIONS> QUALIFICATIONS { get; set; }
        public virtual REQUESTS_STAGES REQUESTS_STAGES { get; set; }
        public virtual REQUESTS_STATUSES REQUESTS_STATUSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SENIORITY> SENIORITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_FILE> SERVICE_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_REQ_COMMITTEES> ST_REQ_COMMITTEES { get; set; }
    }
}
