//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_PROCEDURES
    {
        public long ID { get; set; }
        public long REQ_ID { get; set; }
        public long PROCEDURE_TYPE_ID { get; set; }
        public string REASON { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string CREATION_DATE_H { get; set; }
    
        public virtual PROCEDURES_TYPE PROCEDURES_TYPE { get; set; }
    }
}
