//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_FILE
    {
        public long ID { get; set; }
        public Nullable<long> REQ_ID { get; set; }
        public long DEDUCT_DECISION_TYPE_ID { get; set; }
        public Nullable<long> NUMBER { get; set; }
        public string SERVICE_FILE_NAME { get; set; }
        public string SERVICE_FILE_PATH { get; set; }
        public Nullable<double> SERVICE_POINTS { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual DEDUCTING_DECISIONS_TYPES DEDUCTING_DECISIONS_TYPES { get; set; }
        public virtual REQUESTS REQUESTS { get; set; }
    }
}
