//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_MULT_UNIT
    {
        public long ID { get; set; }
        public long PROV_ID { get; set; }
        public long CIT_ID { get; set; }
        public string MU_NAME { get; set; }
        public string MU_M_NAME { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual LT_CITIES LT_CITIES { get; set; }
        public virtual LT_PROVNCITY LT_PROVNCITY { get; set; }
    }
}
