//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_MRANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ST_MRANK()
        {
            this.COMM_MEM_RANKS = new HashSet<COMM_MEM_RANKS>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> NEXT_RANK { get; set; }
        public Nullable<long> MIN_QUALIFICATION_ID { get; set; }
        public Nullable<long> DURATION_YEARS { get; set; }
        public Nullable<long> CREATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMM_MEM_RANKS> COMM_MEM_RANKS { get; set; }
    }
}
