//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULP_DEPARTMENTS_VU
    {
        public Nullable<long> ID { get; set; }
        public Nullable<long> DEPT_ID { get; set; }
        public string TYPE_MGR_POSITION { get; set; }
        public string DEPT_NAME_A { get; set; }
        public string DEPT_NAME_L { get; set; }
        public Nullable<long> DEPT_MGR { get; set; }
        public long DEPT_TYPE { get; set; }
    }
}
