//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULP_DEPARTMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ULP_DEPARTMENTS()
        {
            this.COMMITTEES = new HashSet<COMMITTEES>();
            this.DIVISIONS = new HashSet<DIVISIONS>();
        }
    
        public long ID { get; set; }
        public string DEPT_NAME_A { get; set; }
        public string DEPT_NAME_L { get; set; }
        public Nullable<long> DEPT_MGR { get; set; }
        public string DEPT_TYPE { get; set; }
        public string TYPE_MGR_POSITION { get; set; }
        public long PROV_ID { get; set; }
        public Nullable<long> CIT_ID { get; set; }
        public long CREATION_USER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMITTEES> COMMITTEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIVISIONS> DIVISIONS { get; set; }
    }
}
