//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ERP_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACANT_JOBS
    {
        public long ID { get; set; }
        public long RANK_ID { get; set; }
        public long MILITARY_NO { get; set; }
        public long FILTRATION_PERIODS_ID { get; set; }
        public Nullable<long> REQ_ID { get; set; }
    }
}
